addons:
  sauce_connect:
    username: ipeychev
    no_ssl_bump_domains: all
  jwt:
    secure: M7ncBcQS/4AG0aqGhpJxQOsZYQsUJCO2nq7FV3JxnUrSQgoy+JExJbxTNs1Aovdms3X70kW5SGNyP2msvPePLmw1tAD/Dv360Xj6emqnsGkTNVpu/4BUGAUTgIvoK66rGqPa5950tyr2SBRA+IAfPLGQvUe/5MxXbMP5c73b5Ac=

language: node_js
node_js:
- '8.7.0'
script:
- 'npm run test:ci'