addons:
  sauce_connect:
    username: wedeploy-sdk-js
    no_ssl_bump_domains: all
  jwt:
    secure: JXl3gbIOP3GS8aFbHJiNWG6cFztLPOiu4RTpPVoHAOqAgLjF/Lh6ZYd0a3++IAoOmj8v/MwTFgOxFuLcK0tfXbDtxeNlvE8D+3ODXUYBsUmLVsibKL/Ea6wkhCIwYoZ8JXkhAn6yDyPVlbmEB4V1fC07VePhfpjvsxypgEE29Is=
language: node_js
node_js:
- '8.7.0'
script:
- 'npm run test:ci'